### PR TITLE
Create a Youtube Clone

### PR DESCRIPTION
**Pull request by fegzycole**
#### What does this PR do?
Creates a webpage aesthetically similar to <http://archive.fo/Bss88#selection-2411.1-2425.15>
#### How should this be manually tested?
Visit the Github pages link on <https://bafiam.github.io/project1-youtubeClone/>

### CODE REVIEW

**Review by Forison — COMMENTED** [review]
# pull request under review by Addo

**Review by Forison — CHANGES_REQUESTED** [review]
# Hi Team,👋👋
## Am impressed at the output of your work👌
your files were well organized, your readme file looks very professional💪. Good application of semantic in the index file💪. 
* [ ]  Kindly add the avatar of the user who uploaded the video

## make this addition and submit for review
## Happy coding💪

**Comment by fegzycole** [comment]
Hello @Forison,

Kindly find attached a screenshot of the application containing the avatar.

Regards

YoutubeClone

**Review by Redvanisation — APPROVED** [review]
### Hello team🌟 

### _Nice work on this project, it seems that you guys have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
